package:
  name: quantecon
  version: !!str 0.1.2

source:
  fn: quantecon-0.1.2.tar.gz
  url: https://pypi.python.org/packages/source/q/quantecon/quantecon-0.1.2.tar.gz
  md5: 245bcef5f18d1afe858cf95453c28934
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  #preserve_egg_dir: True
  #entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - quantecon = quantecon:main
    #
    # Would create an entry point called quantecon that calls quantecon.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
      #    - numpy
      #    - scipy
      #    - pandas

  run:
    - python
    - numpy
    - scipy
    - pandas

test:
  # Python imports
  imports:
    - quantecon

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/jstac/quant-econ
  license: BSD
  summary: 'Code for quant-econ.net'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
